"""Score table

Revision ID: efaebfcaa578
Revises: 9762a4d8e605
Create Date: 2021-05-05 14:45:10.418768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaebfcaa578'
down_revision = '9762a4d8e605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_ID', sa.Integer(), nullable=True),
    sa.Column('Mod_1', sa.Integer(), nullable=True),
    sa.Column('Mod_2', sa.Integer(), nullable=True),
    sa.Column('Mod_3', sa.Integer(), nullable=True),
    sa.Column('finalScore', sa.Integer(), nullable=True),
    sa.Column('totalScore', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['score_ID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sores_Mod_1'), 'sores', ['Mod_1'], unique=False)
    op.create_index(op.f('ix_sores_Mod_2'), 'sores', ['Mod_2'], unique=False)
    op.create_index(op.f('ix_sores_Mod_3'), 'sores', ['Mod_3'], unique=False)
    op.create_index(op.f('ix_sores_finalScore'), 'sores', ['finalScore'], unique=False)
    op.create_index(op.f('ix_sores_totalScore'), 'sores', ['totalScore'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sores_totalScore'), table_name='sores')
    op.drop_index(op.f('ix_sores_finalScore'), table_name='sores')
    op.drop_index(op.f('ix_sores_Mod_3'), table_name='sores')
    op.drop_index(op.f('ix_sores_Mod_2'), table_name='sores')
    op.drop_index(op.f('ix_sores_Mod_1'), table_name='sores')
    op.drop_table('sores')
    # ### end Alembic commands ###
