"""empty message

Revision ID: f914f73ea30e
Revises: efaebfcaa578
Create Date: 2021-05-12 10:38:06.283501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f914f73ea30e'
down_revision = 'efaebfcaa578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sores_Mod_1', table_name='scores')
    op.drop_index('ix_sores_Mod_2', table_name='scores')
    op.drop_index('ix_sores_Mod_3', table_name='scores')
    op.drop_index('ix_sores_finalScore', table_name='scores')
    op.drop_index('ix_sores_totalScore', table_name='scores')
    op.create_index(op.f('ix_scores_Mod_1'), 'scores', ['Mod_1'], unique=False)
    op.create_index(op.f('ix_scores_Mod_2'), 'scores', ['Mod_2'], unique=False)
    op.create_index(op.f('ix_scores_Mod_3'), 'scores', ['Mod_3'], unique=False)
    op.create_index(op.f('ix_scores_finalScore'), 'scores', ['finalScore'], unique=False)
    op.create_index(op.f('ix_scores_totalScore'), 'scores', ['totalScore'], unique=False)
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_scores_totalScore'), table_name='scores')
    op.drop_index(op.f('ix_scores_finalScore'), table_name='scores')
    op.drop_index(op.f('ix_scores_Mod_3'), table_name='scores')
    op.drop_index(op.f('ix_scores_Mod_2'), table_name='scores')
    op.drop_index(op.f('ix_scores_Mod_1'), table_name='scores')
    op.create_index('ix_sores_totalScore', 'scores', ['totalScore'], unique=False)
    op.create_index('ix_sores_finalScore', 'scores', ['finalScore'], unique=False)
    op.create_index('ix_sores_Mod_3', 'scores', ['Mod_3'], unique=False)
    op.create_index('ix_sores_Mod_2', 'scores', ['Mod_2'], unique=False)
    op.create_index('ix_sores_Mod_1', 'scores', ['Mod_1'], unique=False)
    # ### end Alembic commands ###
